package ru.itlab.qa.tests;

// Generated by Selenium IDE

import lombok.SneakyThrows;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;
import ru.itlab.qa.tests.TestBase;

@SpringBootTest
public class QaApplicationLoginTest extends TestBase {

    @SneakyThrows
    @Test
    public void testLogin() {
        login(0);
    }


}
